### ISSUE TITLE
Dials

### ISSUE THREAD

**Issue by 50centbio** [EpicSquid/Embers#12]
Dials doesn't show the amount of liquids or ember. 
Version: 0.230
Os: linux

**Comment by DaedalusGame** [comment]
server? singleplayer? on which machine?

**Comment by 50centbio** [comment]
notebook

**Comment by 50centbio** [comment]
singleplayer

**Comment by DaedalusGame** [comment]
i mean which embers machine are you putting the dial on

**Comment by 50centbio** [comment]
fluid vessel and pressure refinery now imma try putting one on the copper cell

**Comment by 50centbio** [comment]
on the copper cell it works

**Comment by 50centbio** [comment]
ok it' only the fluid on the vessel that doesn't work for the other machine it was me that i put them on the wrong face

**Comment by DaedalusGame** [comment]
![vessel](https://user-images.githubusercontent.com/9559216/41734939-b0fb1a60-7588-11e8-90e3-2d16a2f7ae36.png)

**Comment by 50centbio** [comment]
thank u for the help sorry for the inconvenience at the end it was only me
