### ISSUE TITLE
Item transfers not filtering 

### ISSUE THREAD

**Issue by smooze** [EpicSquid/Embers#18]
I am attempting to make a simple item sorter with Item transfers, however they appear to be allowing items through randomly I am using FTB Revelation 2.2.0 
Image included is of an item transfer made to filter blaze powder allowing zombie flesh to pass through
[https://puu.sh/AX6ro/dd52aac59b.png](url)

**Comment by yutang13** [comment]
Same here. Playing the Exoria pack.
Item transfers don't filter.

**Comment by DaedalusGame** [comment]
Can't reproduce
