### ISSUE TITLE
Crash when destroying machine accessor

### ISSUE THREAD

**Issue by Cronock92** [EpicSquid/Embers#27]
Description:
Game version: 1.12.2
Forge version: 14.23.4.2747
World type: creative, flatworld, no structures
Actions: placed bore one block above bedrock. Placed item pipe to top of bore. Destroyed pipe. Placed machine accessor on output of bore. Tried to destroy machine accessor to replace with mechanical core, game crashed when hitting it. Relaunched game and machine accessor was still on top of bore. Attempted to destroy it again, crash again. Relaunch, machine accessor was removed.

**Comment by Cronock92** [comment]
Yes

**Comment by DaedalusGame** [comment]
fixed a long time ago iirc
