### ISSUE TITLE
Combustion chamber does not take any fuel

### ISSUE THREAD

**Issue by Psion77** [EpicSquid/Embers#29]
In trying to set up the Ignem reactor, I found that I could not get it to work. It seems that the culprit is the combustion chamber. I can put redstone in the catalyse reactor, and ember shards in the ignem reactor, but the combustion chamber does not take the coal. It also does not take nether bricks or blaze powder. 

I first tried using embers pipes. I also tried a hopper.

**Comment by DaedalusGame** [comment]
Fixed
