### ISSUE TITLE
Caminite ring not craftable

### ISSUE THREAD

**Issue by wamc2017** [EpicSquid/Embers#3]
Hi,

looked through the latest commits and I guess the caminite ring is not craftable if the item is removed through this lines (276-279): https://github.com/EpicSquid/Embers/blob/2be77d5e5b89a8cb9d7831b1aece71727c088603/src/main/java/teamroots/embers/block/BlockStoneEdge.java#L276

Thanks for looking into it. :)

Best regards,
wamc

**Comment by DaedalusGame** [comment]
oh yeah that's not good

**Comment by kreezxil** [comment]
I see someone closed the issue on June 15 but the problem still exists today which September 9, 2018 and on version 0.230. I thought I could fix it with Crafttweaker but no matter which recipe I use, it never allows the Caminite Ring to be produced.

**Comment by wamc2017** [comment]
It's fixed in [Embers Rekindled](https://minecraft.curseforge.com/projects/embers-rekindled?gameCategorySlug=mc-mods&projectID=300777) (the continuitation of Embers...)

**Comment by kreezxil** [comment]
thanks. I switched last night and was glad rekindled used the same modid.
