### ISSUE TITLE
Wings, JEI, Embers Incompatibility

### ISSUE THREAD

**Issue by darkshadow543** [EpicSquid/Embers#34]
Here is an error thrown by JEI.
https://pastebin.com/sHJppLEe

I noticed that the Dawnstone Anvil JEI implementation was not working.  Upon Further investigation, I found an error thrown by JEI.  It appears that there is some sort of error on the fixing of wings from the wings mod.

**Comment by DaedalusGame** [comment]
was supposed to be a rekindled issue, fixed
