### ISSUE TITLE
(suggestion):better pipes for embers 2 

### ISSUE THREAD

**Issue by Wotzinator** [EpicSquid/Embers#37]
so i really like the pipes in embers and i hope they will return .my idea is isnpired from enderio with wich i mean is that i would love to the pipes to be able to be put together in one block instead of next to each other.

**Comment by EpicSquid** [comment]
I'm personally not a fan of maintaining 2 mods that both add conduits like ender ios. I have plans for better item and fluid transport, but of you want conduits, I would suggest installing just ender io conduits and enderio base and configuring the recipes with crafttweaker.
