### ISSUE TITLE
Inflictor Gems not Working When Sown into Ashen Cloak

### ISSUE THREAD

**Issue by ElectronsWithBeans** [EpicSquid/Embers#39]
I am using the 1.12.2 version of Embers and when I sow inflictor gems into my ashen cloak, they do nothing. Even after attuning them to a damage. I tested multiple damage types and none have worked. the damage is the same before and after.

**Comment by DaedalusGame** [comment]
you need to wear the entire set

**Comment by ElectronsWithBeans** [comment]
Thanks, that fixed it!
